# Generated by Django 5.2 on 2025-12-02 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('installation', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevisProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire_fcfa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_total_fcfa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.equipement')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis_produits', to='installation.installation')),
            ],
        ),
        migrations.CreateModel(
            name='DimensionnementPV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facteur_rendement', models.DecimalField(decimal_places=2, default=0.6, max_digits=4)),
                ('puissance_unitaire_panneau_w', models.PositiveIntegerField(default=150)),
                ('tension_unitaire_panneau_v', models.PositiveIntegerField(default=12)),
                ('surface_disponible_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('budget_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('avec_stockage', models.BooleanField(default=True)),
                ('capacite_unitaire_batterie_ah', models.PositiveIntegerField(blank=True, null=True)),
                ('tension_unitaire_batterie_v', models.PositiveIntegerField(blank=True, null=True)),
                ('autonomie_jours', models.PositiveIntegerField(blank=True, null=True)),
                ('profondeur_decharge', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('puissance_crete_wc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tension_champ_v', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre_total_panneaux', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre_panneaux_serie', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre_panneaux_parallele', models.PositiveIntegerField(blank=True, null=True)),
                ('capacite_batterie_ah', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nombre_total_batteries', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre_batteries_serie', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre_batteries_parallele', models.PositiveIntegerField(blank=True, null=True)),
                ('puissance_onduleur_w', models.PositiveIntegerField(blank=True, null=True)),
                ('tension_onduleur_v', models.PositiveIntegerField(blank=True, null=True)),
                ('tension_regulateur_v', models.PositiveIntegerField(blank=True, null=True)),
                ('courant_regulateur_a', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('longueur_cable_m', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('section_cable_mm2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('installation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dimensionnement_pv', to='installation.installation')),
            ],
        ),
        migrations.CreateModel(
            name='EquipementDimensionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('temps_utilisation_h', models.DecimalField(decimal_places=2, help_text="Temps d'utilisation par jour en heures", max_digits=5)),
                ('source', models.CharField(choices=[('client', 'Client'), ('technicien', 'Technicien')], default='client', max_length=20)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.equipement')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipements_dimensionnement', to='installation.installation')),
            ],
        ),
    ]
