# Generated by Django 4.2.24 on 2025-10-17 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('installation', '0003_province_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionnementPV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donnees_appareils', models.JSONField()),
                ('irradiation', models.DecimalField(decimal_places=2, default=5.5, max_digits=4)),
                ('facteur_rendement', models.DecimalField(decimal_places=2, default=0.6, max_digits=3)),
                ('tension_batterie', models.DecimalField(decimal_places=2, default=24.0, max_digits=4)),
                ('capacite_batterie', models.DecimalField(decimal_places=2, default=100.0, max_digits=6)),
                ('jours_autonomie', models.PositiveIntegerField(default=2)),
                ('profondeur_decharge', models.DecimalField(decimal_places=2, default=0.8, max_digits=3)),
                ('resultat_calculs', models.JSONField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('installation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dimensionnement', to='installation.installation')),
            ],
            options={
                'verbose_name': 'Dimensionnement photovoltaïque',
                'verbose_name_plural': 'Dimensionnements photovoltaïques',
            },
        ),
    ]
