# Generated by Django 4.2.24 on 2025-10-29 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0003_province_and_more'),
        ('product', '0001_initial'),
        ('installation_pv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimensionnementpv',
            options={},
        ),
        migrations.RemoveField(
            model_name='dimensionnementpv',
            name='capacite_batterie',
        ),
        migrations.RemoveField(
            model_name='dimensionnementpv',
            name='donnees_appareils',
        ),
        migrations.RemoveField(
            model_name='dimensionnementpv',
            name='irradiation',
        ),
        migrations.RemoveField(
            model_name='dimensionnementpv',
            name='jours_autonomie',
        ),
        migrations.RemoveField(
            model_name='dimensionnementpv',
            name='resultat_calculs',
        ),
        migrations.RemoveField(
            model_name='dimensionnementpv',
            name='tension_batterie',
        ),
        migrations.AddField(
            model_name='dimensionnementpv',
            name='autonomie_jours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimensionnementpv',
            name='avec_stockage',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dimensionnementpv',
            name='budget_estime',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='dimensionnementpv',
            name='capacite_batterie_ah',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dimensionnementpv',
            name='capacite_unitaire_batterie_ah',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimensionnementpv',
            name='courant_regulateur_a',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='dimensionnementpv',
            name='longueur_cable_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='dimensionnementpv',
            name='nombre_batteries_parallele',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimensionnementpv',
            name='nombre_batteries_serie',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimensionnementpv',
            name='nombre_panneaux_parallele',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimensionnementpv',
            name='nombre_panneaux_serie',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimensionnementpv',
            name='nombre_total_batteries',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimensionnementpv',
            name='nombre_total_panneaux',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimensionnementpv',
            name='puissance_crete_wc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dimensionnementpv',
            name='puissance_onduleur_w',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimensionnementpv',
            name='puissance_unitaire_panneau_w',
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.AddField(
            model_name='dimensionnementpv',
            name='section_cable_mm2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='dimensionnementpv',
            name='surface_disponible_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='dimensionnementpv',
            name='tension_champ_v',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimensionnementpv',
            name='tension_onduleur_v',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimensionnementpv',
            name='tension_regulateur_v',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimensionnementpv',
            name='tension_unitaire_batterie_v',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimensionnementpv',
            name='tension_unitaire_panneau_v',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='dimensionnementpv',
            name='facteur_rendement',
            field=models.DecimalField(decimal_places=2, default=0.6, max_digits=4),
        ),
        migrations.AlterField(
            model_name='dimensionnementpv',
            name='installation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dimensionnement_pv', to='installation.installation'),
        ),
        migrations.AlterField(
            model_name='dimensionnementpv',
            name='profondeur_decharge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.CreateModel(
            name='EquipementDimensionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('temps_utilisation_h', models.DecimalField(decimal_places=2, help_text="Temps d'utilisation par jour en heures", max_digits=5)),
                ('source', models.CharField(choices=[('client', 'Client'), ('technicien', 'Technicien')], default='client', max_length=20)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.equipement')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipements_dimensionnement', to='installation.installation')),
            ],
        ),
        migrations.CreateModel(
            name='DevisProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire_fcfa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_total_fcfa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.equipement')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis_produits', to='installation.installation')),
            ],
        ),
    ]
