# Generated by Django 5.2 on 2025-07-25 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Catégorie parente (vide si catégorie racine)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='product.categorie')),
            ],
            options={
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('puissance_W', models.DecimalField(blank=True, decimal_places=2, help_text='Puissance nominale en Watts', max_digits=10, null=True)),
                ('tension_V', models.DecimalField(blank=True, decimal_places=2, help_text='Tension nominale en Volts', max_digits=10, null=True)),
                ('frequence_Hz', models.PositiveIntegerField(blank=True, help_text='Fréquence en Hz (pour AC uniquement)', null=True)),
                ('capacite_Ah', models.DecimalField(blank=True, decimal_places=2, help_text='Capacité en Ampère-heures (batteries)', max_digits=10, null=True)),
                ('taille', models.CharField(blank=True, help_text='Taille, volume ou puissance (ex: 180L, 1.5CV, 32 pouces)', max_length=50, null=True)),
                ('type_equipement', models.CharField(blank=True, help_text='Type précis (ex: Gel, MPPT, Hybride)', max_length=100, null=True)),
                ('mode', models.CharField(choices=[('AC', 'Alternatif (AC)'), ('DC', 'Continu (DC)'), ('DC/AC', 'Continu / Alternatif (Hybride)')], help_text="Mode d'alimentation", max_length=10)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipements', to='product.categorie')),
                ('marque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements', to='product.marque')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'ordering': ['categorie', 'nom'],
            },
        ),
    ]
