# Generated by Django 5.2.5 on 2025-08-23 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=150, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='product.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type_equipement', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('puissance_W', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('puissance_VA', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('puissance_nominale_W', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tension_V', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tension_entree_DC_V', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tension_sortie_AC_V', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('frequence_Hz', models.PositiveIntegerField(blank=True, null=True)),
                ('capacite_Ah', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('energie_Wh', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('taille', models.CharField(blank=True, max_length=100)),
                ('taille_mm', models.CharField(blank=True, max_length=100)),
                ('efficacite_module_pourcent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('courant_puissance_max_Imp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('courant_court_circuit_ISC', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tension_puissance_max_VMP', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tension_circuit_ouvert_VOC', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tension_maximale_systeme_V', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tolerance_puissance_W', models.CharField(blank=True, max_length=50)),
                ('temperature_module_fonctionnement_C', models.CharField(blank=True, max_length=50)),
                ('calibre_max_fusibles_serie_A', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cycle_vie_cycles', models.CharField(blank=True, max_length=100)),
                ('ir_initiale_mOhm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('poids_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('forme_onde', models.CharField(blank=True, max_length=50)),
                ('rendement_pourcent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('courant_charge_A', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tension_systeme_V', models.CharField(blank=True, max_length=50)),
                ('tension_max_PV_V', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('puissance_PV_max_12V', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('puissance_PV_max_24V', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('puissance_PV_max_48V', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('caracteristiques_additionnelles', models.JSONField(blank=True, null=True)),
                ('conditions_test', models.CharField(blank=True, max_length=255)),
                ('type_stockage', models.CharField(blank=True, max_length=255)),
                ('description_technique', models.TextField(blank=True)),
                ('mode', models.CharField(blank=True, choices=[('AC', 'Alternatif'), ('DC', 'Continu'), ('DC/AC', 'Hybride')], max_length=10)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipements', to='product.categorie')),
                ('marque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements', to='product.marque')),
            ],
        ),
    ]
