# Generated by Django 5.2 on 2025-12-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='calibre_max_fusibles_serie_A',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='conditions_test',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='temperature_module_fonctionnement_C',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='tension_max_PV_V',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='tolerance_puissance_W',
        ),
        migrations.AddField(
            model_name='equipement',
            name='est_disponible',
            field=models.BooleanField(default=True),
        ),
    ]
