# Generated by Django 5.2 on 2025-12-02 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_equipement_calibre_max_fusibles_serie_a_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='marchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements', to='user.profilmarchand'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='prix_unitaire_fcfa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='quantite_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
