# Generated by Django 5.2 on 2025-12-14 11:48

import django.db.models.deletion
import market.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('installation', '0003_remove_devis_cout_achat_equipements_and_more'),
        ('product', '0003_equipement_marchant_equipement_prix_unitaire_fcfa_and_more'),
        ('user', '0002_alter_user_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=market.models.generate_request_ref, max_length=64, unique=True)),
                ('titre', models.CharField(default='Demande matériel', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée'), ('closed', 'Fermée')], default='draft', max_length=30)),
                ('createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_requests_created', to=settings.AUTH_USER_MODEL)),
                ('destinataires', models.ManyToManyField(blank=True, related_name='requests_received', to='user.profilmarchand')),
                ('installation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical_requests', to='installation.installation')),
                ('technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_requests', to='user.profiltechnicien')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_libre', models.CharField(blank=True, max_length=255, null=True)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('caracteristiques', models.JSONField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('equipement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.equipement')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='market.technicalrequest')),
            ],
        ),
        migrations.CreateModel(
            name='VendorQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=market.models.generer_reference_vq, max_length=64, unique=True)),
                ('date_reponse', models.DateTimeField(auto_now_add=True)),
                ('validite_jours', models.PositiveIntegerField(default=7)),
                ('delai_livraison_jours', models.PositiveIntegerField(default=7)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyée'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée')], default='pending', max_length=30)),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_quotes', to='user.entreprise')),
                ('marchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_quotes', to='user.profilmarchand')),
                ('technical_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_quotes', to='market.technicalrequest')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedVendorQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_selected', models.DateTimeField(auto_now_add=True)),
                ('selected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('technical_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_quote', to='market.technicalrequest')),
                ('vendor_quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='market.vendorquote')),
            ],
        ),
        migrations.CreateModel(
            name='VendorQuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_libre', models.CharField(blank=True, max_length=255, null=True)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire_fcfa', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('prix_total_fcfa', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('disponibilite', models.CharField(blank=True, max_length=100, null=True)),
                ('garantie_mois', models.PositiveIntegerField(blank=True, null=True)),
                ('equipement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.equipement')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='market.vendorquote')),
                ('technical_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.technicalrequestitem')),
            ],
        ),
    ]
