# Generated by Django 5.2 on 2025-12-14 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='created_at',
            new_name='cree_le',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='envoye_le',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='is_seen',
            new_name='lu',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='texte',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='media_file',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AddField(
            model_name='conversation',
            name='est_groupe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='nom_groupe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='expediteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_emis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='chat/'),
        ),
        migrations.DeleteModel(
            name='MessageNotification',
        ),
    ]
