# Generated by Django 5.2 on 2025-07-25 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout_achat_equipements', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cout_installation_main_oeuvre', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cout_maintenance_estime_an', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('fichier_devis_pdf', models.FileField(blank=True, null=True, upload_to='devis_pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consommation_energetique', models.DecimalField(decimal_places=2, max_digits=12)),
                ('province', models.CharField(max_length=100)),
                ('budget_client', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('surface_disponible_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contraintes_specifiques', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('proposed', 'Proposition envoyée'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée'), ('installed', 'Installée'), ('canceled', 'Annulée')], default='pending', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstallationEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SchemaInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_schema', models.FileField(blank=True, null=True, upload_to='schemas/')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComparaisonEconomique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout_electricite_traditionnelle_estime_an', models.DecimalField(decimal_places=2, max_digits=12)),
                ('economies_potentielles_annuelles', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duree_retour_investissement_annees', models.PositiveIntegerField()),
                ('devis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comparaison', to='installation.devis')),
            ],
        ),
    ]
