# Generated by Django 5.2 on 2025-12-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComparaisonEconomique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout_electricite_traditionnelle_estime_an', models.DecimalField(decimal_places=2, max_digits=12)),
                ('economies_potentielles_annuelles', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duree_retour_investissement_annees', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_devis', models.CharField(default='DEVIS-XXXX', max_length=50, unique=True)),
                ('cout_achat_equipements', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cout_installation_main_oeuvre', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cout_maintenance_estime_an', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fichier_devis_pdf', models.FileField(blank=True, null=True, upload_to='devis_pdfs/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_donnees', models.CharField(choices=[('client', 'Fournies par le client'), ('technicien', 'Renseignement manuel par technicien')], default='client', max_length=20)),
                ('budget_client', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('surface_disponible_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contraintes_specifiques', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('proposed', 'Proposition envoyée'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée'), ('installed', 'Installée'), ('canceled', 'Annulée')], default='pending', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstallationEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('source', models.CharField(choices=[('client', 'Client'), ('technicien', 'Technicien')], default='client', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('irradiation', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='SchemaInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_schema', models.FileField(blank=True, null=True, upload_to='schemas/')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
