# Generated by Django 5.2 on 2025-12-02 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('installation', '0001_initial'),
        ('product', '0002_remove_equipement_calibre_max_fusibles_serie_a_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='entreprise',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='devis', to='user.entreprise'),
        ),
        migrations.AddField(
            model_name='comparaisoneconomique',
            name='devis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comparaison', to='installation.devis'),
        ),
        migrations.AddField(
            model_name='installation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='user.profilclient'),
        ),
        migrations.AddField(
            model_name='installation',
            name='technicien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations', to='user.profiltechnicien'),
        ),
        migrations.AddField(
            model_name='devis',
            name='installation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='installation.installation'),
        ),
        migrations.AddField(
            model_name='installationequipement',
            name='equipement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.equipement'),
        ),
        migrations.AddField(
            model_name='installationequipement',
            name='installation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installation.installation'),
        ),
        migrations.AddField(
            model_name='installation',
            name='equipements_proposes',
            field=models.ManyToManyField(through='installation.InstallationEquipement', to='product.equipement'),
        ),
        migrations.AddField(
            model_name='installation',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installations', to='installation.province'),
        ),
        migrations.AddField(
            model_name='schemainstallation',
            name='installation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schema', to='installation.installation'),
        ),
    ]
