# Generated by Django 5.2 on 2025-09-10 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('irradiation', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='installation',
            name='consommation_energetique',
        ),
        migrations.AddField(
            model_name='installation',
            name='source_donnees',
            field=models.CharField(choices=[('client', 'Fournies par le client'), ('technicien', 'Renseignement manuel par technicien')], default='client', max_length=20),
        ),
        migrations.AddField(
            model_name='installationequipement',
            name='source',
            field=models.CharField(choices=[('client', 'Client'), ('technicien', 'Technicien')], default='client', max_length=20),
        ),
        migrations.AlterField(
            model_name='installation',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installations', to='installation.province'),
        ),
    ]
