# Generated by Django 5.2 on 2025-12-14 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0002_initial'),
        ('product', '0003_equipement_marchant_equipement_prix_unitaire_fcfa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devis',
            name='cout_achat_equipements',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='cout_installation_main_oeuvre',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='cout_maintenance_estime_an',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='fichier_devis_pdf',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='installation',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='montant_total',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='numero_devis',
        ),
        migrations.AddField(
            model_name='devis',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='destinataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devis_recus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devis',
            name='emetteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devis_emis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devis',
            name='localisation_client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='nom_client',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ENVOYE', 'Envoyé'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé'), ('TERMINE', 'Terminé')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='devis',
            name='telephone_client',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='titre_projet',
            field=models.CharField(default="Projet d'installation photovoltaïque", max_length=200),
        ),
        migrations.AddField(
            model_name='devis',
            name='type_devis',
            field=models.CharField(choices=[('DEMANDE_TECHNICIEN_A_VENDEUR', 'Demande du technicien au vendeur'), ('REPONSE_VENDEUR_A_TECHNICIEN', 'Réponse du vendeur au technicien'), ('DEVIS_FINAL_AU_CLIENT', 'Devis final envoyé au client')], default='DEMANDE_TECHNICIEN_A_VENDEUR', max_length=40),
        ),
        migrations.CreateModel(
            name='ConditionsDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validite_jours', models.PositiveIntegerField(default=7)),
                ('garantie_installation_mois', models.PositiveIntegerField(default=3)),
                ('modalites_paiement', models.TextField(default='50% avant installation, 50% après mise en service')),
                ('devis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='installation.devis')),
            ],
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('prix_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('disponibilite', models.CharField(blank=True, max_length=100, null=True)),
                ('garantie_mois', models.PositiveIntegerField(blank=True, null=True)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='installation.devis')),
                ('equipement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.equipement')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDevisFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='installation.devis')),
            ],
        ),
    ]
