# Generated by Django 5.2.5 on 2025-08-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_signalisation', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('reported', 'Signalé'), ('diagnosed', 'Diagnostiqué'), ('solution_proposed', 'Solution proposée'), ('resolved', 'Résolu'), ('closed', 'Fermé')], default='reported', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_proposee', models.TextField(blank=True, null=True)),
                ('cout_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('temps_estime_heure', models.PositiveIntegerField(blank=True, null=True)),
                ('date_intervention_prevue', models.DateTimeField(blank=True, null=True)),
                ('date_intervention_reelle', models.DateTimeField(blank=True, null=True)),
                ('rapport_intervention_pdf', models.FileField(blank=True, null=True, upload_to='maintenance_reports/')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte_question', models.TextField()),
                ('type_question', models.CharField(choices=[('diagnostic', 'Diagnostic initial'), ('follow_up', 'Suivi')], default='diagnostic', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ReponseMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.TextField()),
                ('date_reponse', models.DateTimeField(auto_now_add=True)),
                ('repondu_par_client', models.BooleanField(default=False)),
                ('repondu_par_technicien', models.BooleanField(default=False)),
            ],
        ),
    ]
