# Generated by Django 5.2.5 on 2025-08-23 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('installation', '0002_initial'),
        ('maintenance', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents_signales', to='user.profilclient'),
        ),
        migrations.AddField(
            model_name='incident',
            name='installation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='installation.installation'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='maintenance.incident'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='technicien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to='user.profiltechnicien'),
        ),
        migrations.AddField(
            model_name='reponsemaintenance',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_diagnostic', to='maintenance.incident'),
        ),
        migrations.AddField(
            model_name='reponsemaintenance',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.questionmaintenance'),
        ),
    ]
