# Generated by Django 5.2 on 2025-12-14 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RenameField(
            model_name='profilclient',
            old_name='nombre_recommandations',
            new_name='nombre_avis',
        ),
        migrations.RenameField(
            model_name='profilmarchand',
            old_name='nombre_produits',
            new_name='nombre_avis',
        ),
        migrations.RemoveField(
            model_name='profilclient',
            name='points_fidelite',
        ),
        migrations.RemoveField(
            model_name='profilmarchand',
            name='points_fidelite_clients',
        ),
        migrations.RemoveField(
            model_name='profilmarchand',
            name='ventes_totales',
        ),
        migrations.RemoveField(
            model_name='profiltechnicien',
            name='installations_realisees',
        ),
        migrations.AddField(
            model_name='profilclient',
            name='note_moyenne',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='profilmarchand',
            name='note_moyenne',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_donnes', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_recus', to='user.profilclient')),
                ('marchand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_recus', to='user.profilmarchand')),
                ('technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_recus', to='user.profiltechnicien')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
