# Generated by Django 5.2 on 2025-07-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiltechnicien',
            name='autorisation_docs',
            field=models.FileField(blank=True, null=True, upload_to='technician_docs/autorisations/'),
        ),
        migrations.AddField(
            model_name='profiltechnicien',
            name='autres_docs',
            field=models.FileField(blank=True, null=True, upload_to='technician_docs/autres/'),
        ),
        migrations.AddField(
            model_name='profiltechnicien',
            name='formation_document',
            field=models.FileField(blank=True, null=True, upload_to='technician_docs/formations/'),
        ),
    ]
